### ISSUE TITLE
Request: runConfigurations independent of melos installation option

### ISSUE THREAD

**Issue by 2ZeroSix** [invertase/melos#109]
melos generates idea run configurations only for global installation
https://github.com/invertase/melos/blob/84ccf5aaffdc286a270065d84ae5084d9d95d805/packages/melos/lib/src/common/intellij_project.dart#L192-L200

It's much safer to control dependencies in root `pubspec.yaml`
```yaml
dev_dependencies:
  melos: ^0.4.11
```

but `bootstrap` generates melos specific `runConfigurations` as follows
```xml
    <option name="SCRIPT_PATH" value="$USER_HOME$/.pub-cache/bin/melos" />
    <option name="SCRIPT_OPTIONS" value="bootstrap" />
```

it could be changed to something like this to be  independent of installation option
```xml
    <option name="SCRIPT_PATH" value="$PROJECT_DIR$/.fvm/flutter_sdk/bin/dart" />
<!--<option name="SCRIPT_PATH" value="<flutter-sdk-path>/bin/dart" />-->
    <option name="SCRIPT_OPTIONS" value="pub run melos bootstrap" />
```
I suppose it's linked to #81 since this requires proper flutter sdk path

**Comment by Salakar** [comment]
This makes sense, we probably shouldn't be using hardcoded paths like that 

I'd need to spend some time investigating possible solutions for this

**Comment by matecode** [comment]
Just stumbled over this issue, is this still in scope? Would be great to respect the sdkPath from #81 @Salakar. Thanks in advance <3

**Comment by spydon** [comment]
> Just stumbled over this issue, is this still in scope? Would be great to respect the sdkPath from #81 @Salakar. Thanks in advance <3

Sure, it's still in scope. Is it something that you would like to implement? :)

**Comment by matecode** [comment]
I had a look into the code and i couldn't figure out how to solve that. 

The runConfigurations need a binary, but in sdkPath there is no melos binary to call, it only lives in global pub-cache. For me this results in kernel binary errros when running melos (because dart is 3.4.2 globally installed together with fvm, and flutter has dart 3.4.1 bundled). 

All together maybe it makes no sense because after calling melos is anyway switching to a local version?  @spydon

**Comment by spydon** [comment]
I'll close this for now, if anyone comes up with a better solution we can re-open it.
