### ISSUE TITLE
melos format output unredable on Windows 

### ISSUE THREAD

**Issue by feinstein** [invertase/melos#11]
Running the `melos format` command on IntelliJ IDEA on Windows 10, I get this output:

![image](https://user-images.githubusercontent.com/8120472/92344528-14ef9a00-f09d-11ea-8801-67cdbafc3c3e.png)

Which isn't very meaningful.

**Comment by Salakar** [comment]
This is the output coming from `flutter_plugin_tools` unfortunately, not from melos

**Comment by feinstein** [comment]
@Salakar I opened an issue at the Flutter repo to report this.

PS: Are you getting my messages? I had issues with github's email system and since I didn't get any responses from you on [this PR](https://github.com/FirebaseExtended/flutterfire/pull/3334) you asked me to fix, I am wondering if you also don't have the same problem.

**Comment by feinstein** [comment]
@Salakar take a look there if you can, Stuart thinks it might be related on how `flutter_plugin_tools format` is been called on Windows.

**Comment by Salakar** [comment]
Going to close this as `flutter_plugin_tools` has now been deprecated. So we'll look to moving formatting away from this on FlutterFire etc.

**Comment by stuartmorgan** [comment]
> Going to close this as `flutter_plugin_tools` has now been deprecated. So we'll look to moving formatting away from this on FlutterFire etc.

FYI we'll be walking this deprecation back slightly, and the package will be updated soon to reflect the new plan. It will continue to be supported as a package since it's used in multiple flutter/* repositories, it just won't be explicitly supported as a general-purpose tool. I wouldn't expect any issues with continuing to use the tool's `format` command here.
