### ISSUE TITLE
Question: Facing performance issues with large codebase

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#119]
Hey @Salakar and @rrousselGit 
I have integrated `melos` into my project which consists of 25 packages currently. I am seeing the following command runs really slow:
```
melos bootstrap
```
and 
```
test: melos exec --fail-fast -- flutter test --coverage
```
<img width="759" alt="Screenshot 2021-06-02 at 1 14 03 PM" src="https://user-images.githubusercontent.com/14856659/120443584-6a46a680-c3a4-11eb-99ca-ac4de970041b.png">

Why does `melos run test` takes a lot of time to load a test?

**Comment by Salakar** [comment]
Any actions that 'touch' `pub` which includes `flutter test` (since I believe it does a check on whether it needs to run `flutter pub get` first) are gated behind a single concurrency file lock by pub since it has to read/write to the packages cache etc locally without contention. 

This is not something Melos can do anything about, however I'd recommend using the `--concurrency=1` flag on `melos exec` and run your packages serially one by one on commands that involve pub.

**Comment by SAGARSURI** [comment]
Thanks @Salakar for the reply!
