### ISSUE TITLE
Testing in VSCode invalidates melos

### ISSUE THREAD

**Issue by smkhalsa** [invertase/melos#170]
Every time I try to run a test in VSCode (and after running `melos bs`), it appears to revert to using the pubspec dependencies.

I have two packages, A & B.

If I:
1. run `melos bs`
2. edit the API of A
3. edit B to use A's new API

Everything looks good. However, when I then run a test in B, it reverts everything to use the version of A from my pubspec.

**Comment by Salakar** [comment]
My guess is test is running `pub get` since it thinks dependencies aren't in sync - might be the same issue as #117 sorry 🙈 

@rrousselGit I think there's potentially a few more places is Dart/Flutter tooling that needs to respect the `generated by` texts, e.g. https://github.com/invertase/melos/issues/117#issuecomment-913559097 - is this something that's fixable do you think?

**Comment by rrousselGit** [comment]
That's probable. I'm sure it can be fixed, although I don't think I have some time for it in the short term.

**Comment by smkhalsa** [comment]
> My guess is test is running pub get since it thinks dependencies aren't in sync

Yea, that was my assumption.

> I'm sure it can be fixed, although I don't think I have some time for it in the short term.

😕 Sounds like I might have switched to `melos` prematurely since running tests and `build_runner` are both important to my workflow.

**Comment by smkhalsa** [comment]
Not being able to use VSCode to test packages in my monorepo with local dependencies is creating a lot of friction in my workflow.

Any estimate on when this might be fixed? Thanks

**Comment by rrousselGit** [comment]
We're a bit busy at the moment.
If you want to help, feel free to track down what is executing `pub get`.

**Comment by blaugold** [comment]
The VSCode Dart extension uses `dart run` to execute tests, which currently does not allow dependencies resolved by third-party tools. Like @Salakar mentioned in https://github.com/invertase/melos/issues/170#issuecomment-915094536, the underlying problem is the same for this issue and #117. I have created a PR (https://github.com/invertase/melos/issues/117#issuecomment-955172143), that if and when merged should fix both issues.

**Comment by blaugold** [comment]
Please see https://github.com/invertase/melos/issues/117#issuecomment-1125224468 for a solution for this issue.
