### ISSUE TITLE
Melos exec sequentially.

### ISSUE THREAD

**Issue by wangmir** [invertase/melos#223]
I have a problem on using melos at github action.
I read article about melos (https://medium.com/flutter-community/managing-multi-package-flutter-projects-with-melos-c8ce96fa7c82),
and I tried to combine coverage of different project into single one, but in that case it occasionally raise a problem.

melos seems to launch exec for each package at the same time with multiple thread, thus combining lcov.info into single file derive conflict in some cases. 

So, how about support sequential execution option for this?

**Comment by blaugold** [comment]
You can control the concurrency of `exec` with the [`-c`](https://melos.invertase.dev/commands/exec#concurrency--c) flag. `melos exec -c 1 ...` executes the command in packages sequentially.

**Comment by marcotas** [comment]
How would this be possible using `melos.yaml` file? I didn't figure this out.

**Comment by wangmir** [comment]
@marcotas check this out.

```yaml
  gen_coverage:
    run: |
      rm -rf "\$MELOS_ROOT_PATH/coverage_report"
      melos exec -c 1 -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
      genhtml coverage_report/lcov.info -o coverage_report/html

```

**Comment by marcotas** [comment]
Thanks @wangmir! Yeah, after a quick read at melos' doc i also figured this out:
```yaml
  test:
    run: |
      dart pub global run coverage:test_with_coverage && $MELOS_ROOT_PATH/tool/combine_coverage.sh
    exec:
      concurrency: 1
```
This is a very simple "run all tests in all packages with coverage and then combine them all". The `concurrency` was needed because it seems dart VM runs a server at the same port so tests with Melos must be sequential. I think this will be helpful for someone else trying to do the same thing in the future.
