### ISSUE TITLE
request:  Use melos in a single-package repo

### ISSUE THREAD

**Issue by ookami-kb** [invertase/melos#502]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

I use melos in a single-package repository for stuff like creating a publishing a new version. With melos pre v3, I was able to set it up like this:

```yml
packages:
  - '**'
```

Starting with v3, melos requires to be added to `dev_dependencies` which is fine, but it doesn't see the top-level "main" project. E.g. with a setup like that:

```
- example/
  - pubspec.yaml
- melos.yaml
- pubspec.yaml
```

running `melos list` shows only `example` package.

Expected behavior: it should show bother top-level and example packages, as it was in v2.

### Reasoning

Useful because melos could be used in a single-project repo without nesting it into the `packages` folder.

**Comment by blaugold** [comment]
Package discovery was optimized in v3 to improve startup times. We probably missed handling packages at the repository root through glob patterns. You should still be able to include a package at the repository root by adding a direct path to it to `pckages`:

```yaml
packages:
  - '.'
```

**Comment by ookami-kb** [comment]
Thanks for the quick response, it really works this way 👍

**Comment by Statyk7** [comment]
We are seeing issues with a Flutter project at the root level, it seems that a 'pub get' is done on the root pubspec, but we have dependencies there to other packages, and we get the error:
`Because [root_package] depends on [child_package] any which doesn't exist (could not find package [child_package] at https://pub.dev), version solving failed.`

To fix it we have to add the path directive to the pubspec, which kills the main purpose of using melos...
I plan to move the root package to a sub folder to see if it solves the issue but we have it like that for other reasons.

**Comment by spydon** [comment]
> We are seeing issues with a Flutter project at the root level, it seems that a 'pub get' is done on the root pubspec, but we have dependencies there to other packages, and we get the error: `Because [root_package] depends on [child_package] any which doesn't exist (could not find package [child_package] at https://pub.dev), version solving failed.`
> 
> To fix it we have to add the path directive to the pubspec, which kills the main purpose of using melos... I plan to move the root package to a sub folder to see if it solves the issue but we have it like that for other reasons.

If you have this in your `pubspec.yaml` it should work after you have run `melos bootstrap`:
```yaml
packages:
  - '.'
```
But it is not recommended to have a project at the root level since you are then bound to the same dependency restrictions as are imposed in the workspace `pubspec.yaml` which is for Melos, so I would recommend moving your package into `packages/` or similar.
