### ISSUE TITLE
Is it possible to configure pre-push or pre-commit git hooks?

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#99]
Hey, thank you for this amazing tool. I have a question though regarding pre-push and pre-commit hooks. 
Is it possible to configure those using melos?

**Comment by Salakar** [comment]
Melos doesn't automatically push commits so that one currently is not doable through melos.

As for pre-commit, we have `version` and `postversion` named scripts currently, but you could easily add support for a `precommit` named script here;

https://github.com/invertase/melos/blob/master/packages/melos/lib/src/command/version.dart#L569

by adding the following just before that commit line;

```dart
    if (currentWorkspace.config.scripts.exists('precommit')) {
      logger.stdout('Running "precommit" lifecycle script...\n');
      await MelosCommandRunner.instance.run(['run', 'precommit']);
    }
```

Then in your projects `melos.yaml` you just need to define a `precommit` that does whatever you need it to do. 

PRs would be welcome for this, and you can easily switch out your currently installed melos for a development one to try this out locally by following the steps here; https://github.com/invertase/melos#local-development-setup

**Comment by SAGARSURI** [comment]
closing this issue because I was able to achieve the same with another plugin i.e lefthook.
